### ISSUE TITLE
Amazon s3 image is not writing into cell

### ISSUE THREAD

**Issue by sathishthandavan** [cxn03651/writeexcel#43]
"*** ERROR: exception Couldn't locate http://s3.amazonaws.com/****alamy.jpg?1426000192: $!"

Code:
 @worksheet.insert_image("A#{row_name}",usage.asset.image(:small))
 #usage.asset.image(:small) - s3 url in string class

**Comment by cxn03651** [comment]
Worksheet#insert_image handles image file on local filesystem such as /tmp/image.jpg, c:\image.png.

**Comment by sathishthandavan** [comment]
Thank you for the update, So I will get the image from amazon s3 and write into temp file.
